name: Coverage Upload

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  id-token: write

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          # Remove root_dir - let codecov figure it out
          override_commit: ${{ github.sha }}
          override_branch: ${{ github.ref_name }}
          commit_parent: true
          slug: marcosomma/orka-reasoning
          verbose: true
          # Add this to help with path mapping
          working-directory: .